### ISSUE TITLE
Error in the format of mathematical operations. (SCSS)

### ISSUE THREAD

**Issue by GiancarloAparicio** [neoclide/coc-prettier#111]
Mathematical operations in CSS can be written in parentheses or with calc, together or with spaces and there is no problem.

```css
 witdth: (20% / 5);
 witdth: calc(20% / 5); 
 witdth: calc(20%*5); 
```
But the mathematical operations in SCSS must always be together otherwise the compiler does not work.

```scss
 $width:5;
 ...
 width: calc(20% / $width);  /* Browser error:  width: calc(20% / $width) */
 width: 20% / $width;          /* Browser error:  width: 20% / $width */

 /* Must be */ 
 width: calc(20%/$width);
 width: 20%/$width;
```

In my case it happens to me with this code. When formatting, it separates mathematical expressions.
```scss
 @for $i from 0 through $numImg-1 {
      #{100%/$numImg * ($i+1)}{
        transform: translate3D(-100%*$i,0,0);  
      }
    }
```
